spring:
  application:
    name: eureka

eureka:
  client:
    register-with-eureka: false # eureka ??? ?? eureka ??? ???? ??
    fetch-registry: false # eureka ??? ?? eureka ??? ??? ???? ??

server:
  port: 8761


